### ISSUE TITLE
Parse errors in patterns

### ISSUE THREAD

**Issue by egisatoshi** [egison/egison#140]
I found the following expressions cannot be parsed by the new parser.

```
matchAll -1 as integer with
| #-1 -> "Matched"

matchAll (1,2) as unorderedPair integer with
| pair _ !#2 -> "Matched"
```

**Comment by momohatt** [comment]
The first one needs parenthesis around `-1` (and I think it is natural to require parenthesis here)
```
matchAll -1 as integer with
| #(-1) -> "Matched"
```

**Comment by momohatt** [comment]
As for the second one, it happens because the current parser treats not pattern operator `!` similarly as the negative sign operator `-` in expression. Making the second example work in the new parser will require the following case to be rejected. If this still seems fine, I'll make a patch to fix this.
```
> matchAll [1,2,3] as list integer with ! cons #2 _ -> True
[True]
```

**Comment by egisatoshi** [comment]
Thank you very much!
OK. I add parenthesis around `-1` in the value pattern.
I feel the parenthesis around a pattern after `!` (such as `!(cons #2 _)` ) seems fine.
